version: "3.9"
services:
  postgres_db:
    image: postgres
    env_file:
      - ecom/.env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: