# Generated by Django 3.2.18 on 2023-04-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230416_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ItemImage',
        ),
    ]
