# Generated by Django 3.2.18 on 2023-04-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='album',
        ),
        migrations.RemoveField(
            model_name='product',
            name='album',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='product',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImageAlbum',
        ),
    ]
