# Generated by Django 3.2.18 on 2023-04-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ST', 'STAFF'), ('CUST', 'CUSTOMER')], default='STAFF', max_length=8),
            preserve_default=False,
        ),
    ]
